name: Sync Submodules

on:
  repository_dispatch:
    types: [submodule-update]
  workflow_dispatch:
  schedule:
    # Optional: Run every hour to check for updates
    - cron: "0 * * * *"

jobs:
  sync-submodules:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout master repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          submodules: recursive

      - name: Update submodules to latest main
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'

          # Update all submodules to their latest main branch
          git submodule foreach '
            echo "Updating submodule: $name"
            git fetch origin
            git checkout main
            git pull origin main
          '

      - name: Check if there are changes
        id: verify-changed-files
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Commit and push changes
        if: steps.verify-changed-files.outputs.changed == 'true'
        run: |
          git add .
          git commit -m "Auto-update submodules to latest main commits"
          git push origin main
